version: '3'
services:
  db:
    image: postgres:11
    env_file:
      - .env
    volumes:
      - db-content:/var/lib/postgresql/data
    networks:
      - overlay

  django:
    image: epickiwi/nopls-django
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
      - VERSION=${VERSION}
    depends_on:
      - db
    volumes:
      - user-media:/code/user-media
      - static-files:/code/static-files
    networks:
      - overlay
    deploy:
      replicas: 1

  proxy:
    image: epickiwi/bdecesi-proxy
    volumes:
      - user-media:/var/media
      - static-files:/var/static
    depends_on:
      - django
      - db
    networks:
      - overlay
      - traefik-net
    deploy:
      replicas: 1
      labels:
        traefik.enable: "true"
        traefik.http.services.bde-cesi.loadbalancer.server.port: "80"

        traefik.http.routers.no-pls.entrypoints: web-secure
        traefik.http.routers.no-pls.rule: "Host(`nopls.epickiwi.fr`)"
        traefik.http.routers.no-pls.tls.certresolver: letsencrypt

        traefik.http.routers.no-pls-insecure.entrypoints: web
        traefik.http.routers.no-pls-insecure.rule: "Host(`nopls.epickiwi.fr`)"
        traefik.http.routers.no-pls-insecure.middlewares: force-https@file

volumes:
  user-media:
  db-content:
  static-files:

networks:
  overlay:
  traefik-net:
    external: true