version: 2
jobs:
  build:
    branches:
      only:
       - master
    docker:
      - image: lgatica/openssh-client
    steps:
      - add_ssh_keys:
          fingerprints:
            - "9a:f3:0c:d8:78:68:3e:5c:7c:05:0a:e0:8e:bf:2d:f8"
      - run:
          name: deploy
          command: ssh -oStrictHostKeyChecking=no epickiwi@epickiwi.fr "cd nuit-info-2019 && ./deploy.sh"