# Generated by Django 3.0 on 2019-12-06 01:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('procedures', '0002_auto_20191206_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='helpers',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
