# Generated by Django 3.0 on 2019-12-06 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0004_auto_20191206_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentstep',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='procedures.File'),
        ),
    ]
