# Generated by Django 3.0 on 2019-12-06 02:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0006_auto_20191206_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.CharField(default=datetime.datetime(2019, 12, 6, 2, 7, 22, 50434, tzinfo=utc), max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
