# Generated by Django 3.0 on 2019-12-06 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0007_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='contentStep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='procedures.ContentStep'),
        ),
        migrations.AlterField(
            model_name='step',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='procedures.Article'),
        ),
    ]
