# Generated by Django 3.0 on 2019-12-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0008_auto_20191206_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, to='procedures.Tag'),
        ),
    ]
